api_categorias:
    type:     rest
    resource: "@CSPApiBundle/Controller/CategoriasRESTController.php"
    prefix: /api
        
api_productos:
    type:     rest
    resource: "@CSPApiBundle/Controller/ProductosRESTController.php"
    prefix: /api
        
api_proveedores:
    type:     rest
    resource: "@CSPApiBundle/Controller/ProveedoresRESTController.php"
    prefix: /api

api_empleados:
    type:     rest
    resource: "@CSPApiBundle/Controller/EmpleadosRESTController.php"
    prefix: /api
        
api_clientes:
    type:     rest
    resource: "@CSPApiBundle/Controller/ClientesRESTController.php"
    prefix: /api

csp_base:
    resource: "@CSPBaseBundle/Controller/"
    type:     annotation
    prefix:   /

csp_generico:
    resource: "@CSPGenericoBundle/Controller/"
    type:     annotation
    prefix:   /
    
csp_api:
    resource: "@CSPApiBundle/Controller/"
    type:     annotation
    prefix:   /
    
csp_cliente:
    resource: "@CSPClienteBundle/Controller/"
    type:     annotation
    prefix:   /

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc