security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_API:         ~
        ROLE_USER:        ~
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: fos_userbundle
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            anonymous: true
            
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/productos, role: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/proveedores, role: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/clientes, role: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/categorias, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/empleados, role: [ROLE_ADMIN] }

        #- { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/APIClient, roles: [ ROLE_API ] }